Repository opencv/opencv_zoo, pull requests merged in 2022-09, with the labels that each got.

#83 Add hand pose estimation model from Mediapipe
  README.md
  benchmark/config/handpose_estimation_mediapipe.yaml
  benchmark/download_data.py
  models/__init__.py
  models/handpose_estimation_mediapipe/LICENSE
  models/handpose_estimation_mediapipe/README.md
  models/handpose_estimation_mediapipe/demo.py
  models/handpose_estimation_mediapipe/examples/hand_keypoints.png
  models/handpose_estimation_mediapipe/examples/mphandpose_demo.gif
  models/handpose_estimation_mediapipe/handpose_estimation_mediapipe_2022may-int8-quantized.onnx
  models/handpose_estimation_mediapipe/handpose_estimation_mediapipe_2022may.onnx
  models/handpose_estimation_mediapipe/mp_handpose.py
  tools/quantize/inc_configs/mp_handpose.yaml
  tools/quantize/quantize-inc.py
  tools/quantize/quantize-ort.py
  tools/quantize/requirements.txt
Labels: add model

#89 text_recognition example argparse bug fix
  models/text_recognition_crnn/demo.py
Labels: bug

#71 Text Recognition: Add script to evaluate text recognition by ICDAR2003
  models/text_recognition_crnn/README.md
  models/text_recognition_crnn/charset_94_CH.txt
  models/text_recognition_crnn/crnn.py
  models/text_recognition_crnn/text_recognition_CRNN_CH_2021sep.onnx
  tools/eval/README.md
  tools/eval/datasets/__init__.py
  tools/eval/datasets/icdar.py
  tools/eval/datasets/iiit5k.py
  tools/eval/eval.py
Labels: GSoC, evaluation

#79 crnnFP16
  models/text_recognition_crnn/text_recognition_CRNN_CH_FP16.onnx
  models/text_recognition_crnn/text_recognition_CRNN_EN_FP16.onnx
Labels: GSoC
