Repository opencv/opencv_zoo, pull requests merged in 2022-08, with the labels that each got.

#80 Update benchmarking results on arm platform (RPI-CPU)
  README.md
Labels: benchmark

#85 Let mp_palmdet support multiple palms detection
  benchmark/config/palm_detection_mediapipe.yaml
  models/palm_detection_mediapipe/demo.py
  models/palm_detection_mediapipe/examples/mppalmdet_demo.gif
  models/palm_detection_mediapipe/mp_palmdet.py
Labels: enhancement

#88 Use QuantFormat.QOperator by default to avoid fake quantization
  tools/quantize/quantize-ort.py
Labels: bug
