Repository opencv/opencv_zoo, pull requests merged in 2022-10, with the labels that each got.

#96 Add resize back code in text detection and recognization demo.
  models/text_detection_db/demo.py
  models/text_recognition_crnn/demo.py
Labels: enhancement

#97 Update benchermark and quantize
  benchmark/README.md
  benchmark/benchmark.py
  tools/quantize/requirements.txt
Labels: documentation

#98 add crnn int8(EN)
  models/text_recognition_crnn/README.md
  models/text_recognition_crnn/text_recognition_CRNN_CH_2021sep.onnx
  models/text_recognition_crnn/text_recognition_CRNN_CH_2022oct_fp16.onnx
  models/text_recognition_crnn/text_recognition_CRNN_CH_2022oct_int8.onnx
  models/text_recognition_crnn/text_recognition_CRNN_EN_2021sep-act_int8-wt_int8-quantized.onnx
  models/text_recognition_crnn/text_recognition_CRNN_EN_2022oct_fp16.onnx
  models/text_recognition_crnn/text_recognition_CRNN_EN_2022oct_int8.onnx
Labels: add model
