Repository opencv/opencv_zoo, pull requests merged in 2022-06, with the labels that each got.

#56 Add LPD_YuNet for License Plate Detection
  README.md
  benchmark/config/license_plate_detection_yunet.yaml
  benchmark/download_data.py
  models/__init__.py
  models/license_plate_detection_yunet/LICENSE
  models/license_plate_detection_yunet/README.md
  models/license_plate_detection_yunet/demo.py
  models/license_plate_detection_yunet/license_plate_detection_lpd_yunet_2022may-int8-quantized.onnx
  models/license_plate_detection_yunet/license_plate_detection_lpd_yunet_2022may.onnx
  models/license_plate_detection_yunet/lpd_yunet.py
  tools/quantize/inc_configs/lpd_yunet.yaml
  tools/quantize/quantize-inc.py
Labels: add model

#58 Fix DB net
  models/text_detection_db/demo.py
Labels: bug

#59 Add example outputs and display in README
  README.md
  models/face_detection_yunet/README.md
  models/face_detection_yunet/examples/largest_selfie.jpg
  models/face_detection_yunet/examples/yunet_demo.gif
  models/human_segmentation_pphumanseg/README.md
  models/human_segmentation_pphumanseg/examples/messi.jpg
  models/human_segmentation_pphumanseg/examples/pphumanseg_demo.gif
  models/license_plate_detection_yunet/README.md
  models/license_plate_detection_yunet/examples/result-1.jpg
  models/license_plate_detection_yunet/examples/result-2.jpg
  models/license_plate_detection_yunet/examples/result-3.jpg
  models/license_plate_detection_yunet/examples/result-4.jpg
  models/object_tracking_dasiamrpn/README.md
  models/object_tracking_dasiamrpn/examples/dasiamrpn_demo.gif
  models/palm_detection_mediapipe/README.md
  models/palm_detection_mediapipe/examples/mppalmdet_demo.gif
  models/qrcode_wechatqrcode/README.md
  models/qrcode_wechatqrcode/examples/wechat_qrcode_demo.gif
Labels: documentation

#60 Add the missing yaml config for quantizing MP-PalmDet and improve quantized MP-PalmDet
  models/palm_detection_mediapipe/README.md
  models/palm_detection_mediapipe/palm_detection_mediapipe_2022may-int8-quantized.onnx
  tools/quantize/inc_configs/mp_palmdet.yaml
  tools/quantize/quantize-inc.py
Labels: bug

#61 Add more demos to front page
  README.md
  models/license_plate_detection_yunet/README.md
  models/license_plate_detection_yunet/examples/lpd_yunet_demo.gif
Labels: documentation
