Repository opencv/opencv_zoo, pull requests merged in 2023-06, with the labels that each got.

#163 Add additional hardware notes in the frontal readme
  README.md
  benchmark/README.md
Labels: documentation

#161 update and modify documentation
  README.md
  benchmark/README.md
  models/face_detection_yunet/README.md
  models/facial_expression_recognition/README.md
  models/handpose_estimation_mediapipe/README.md
  models/human_segmentation_pphumanseg/README.md
  models/license_plate_detection_yunet/README.md
  models/object_detection_nanodet/README.md
  models/object_detection_yolox/README.md
  models/object_tracking_dasiamrpn/README.md
  models/palm_detection_mediapipe/README.md
  models/person_detection_mediapipe/README.md
  models/person_reid_youtureid/README.md
  models/person_reid_youtureid/demo.py
  models/qrcode_wechatqrcode/README.md
  models/text_detection_db/README.md
  models/text_recognition_crnn/README.md
  tools/eval/README.md
Labels: documentation

#151 update yunet to v2
  models/face_detection_yunet/README.md
  models/face_detection_yunet/demo.cpp
  models/face_detection_yunet/demo.py
  models/face_detection_yunet/face_detection_yunet_2022mar.onnx
  models/face_detection_yunet/face_detection_yunet_2022mar_int8.onnx
  models/face_detection_yunet/face_detection_yunet_2023mar.onnx
  models/face_detection_yunet/face_detection_yunet_2023mar_int8.onnx
  models/face_recognition_sface/demo.py
  models/facial_expression_recognition/demo.py
  tools/eval/eval.py
Labels: update model, benchmark

#164 update generate table script
  benchmark/README.md
  benchmark/color_table.svg
  benchmark/generate_table.py
  benchmark/table_config.yaml
Labels: documentation

#166 Add back example output images as lfs tracked files
  .gitattributes
  README.md
  models/face_detection_yunet/README.md
  models/face_detection_yunet/example_outputs/largest_selfie.jpg
  models/face_detection_yunet/example_outputs/yunet_demo.gif
  models/facial_expression_recognition/README.md
  models/facial_expression_recognition/example_outputs/selfie.jpg
  models/handpose_estimation_mediapipe/README.md
  models/handpose_estimation_mediapipe/example_outputs/hand_keypoints.png
  models/handpose_estimation_mediapipe/example_outputs/mphandpose_demo.webp
  models/human_segmentation_pphumanseg/README.md
  models/human_segmentation_pphumanseg/example_outputs/messi.jpg
  models/human_segmentation_pphumanseg/example_outputs/pphumanseg_demo.gif
  models/license_plate_detection_yunet/README.md
  models/license_plate_detection_yunet/example_outputs/lpd_yunet_demo.gif
  models/license_plate_detection_yunet/example_outputs/result-1.jpg
  models/license_plate_detection_yunet/example_outputs/result-2.jpg
  models/license_plate_detection_yunet/example_outputs/result-3.jpg
  models/license_plate_detection_yunet/example_outputs/result-4.jpg
  models/object_detection_nanodet/README.md
  models/object_detection_nanodet/example_outputs/1_res.jpg
  models/object_detection_nanodet/example_outputs/2_res.jpg
  models/object_detection_nanodet/example_outputs/3_res.jpg
  models/object_detection_nanodet/example_outputs/WebCamR.gif
  models/object_detection_yolox/README.md
  models/object_detection_yolox/example_outputs/1_res.jpg
  models/object_detection_yolox/example_outputs/2_res.jpg
  models/object_detection_yolox/example_outputs/3_res.jpg
  models/object_tracking_dasiamrpn/README.md
  models/object_tracking_dasiamrpn/example_outputs/dasiamrpn_demo.gif
  models/palm_detection_mediapipe/README.md
  models/palm_detection_mediapipe/example_outputs/mppalmdet_demo.gif
  models/person_detection_mediapipe/README.md
  models/person_detection_mediapipe/example_outputs/mppersondet_demo.webp
  models/pose_estimation_mediapipe/README.md
  models/pose_estimation_mediapipe/example_outputs/mpposeest_demo.webp
  models/pose_estimation_mediapipe/example_outputs/pose_landmarks.png
  models/qrcode_wechatqrcode/README.md
  models/qrcode_wechatqrcode/example_outputs/wechat_qrcode_demo.gif
  models/text_detection_db/README.md
  models/text_detection_db/example_outputs/gsoc.jpg
  models/text_detection_db/example_outputs/mask.jpg
  models/text_recognition_crnn/README.md
  models/text_recognition_crnn/example_outputs/CRNNCTC.gif
  models/text_recognition_crnn/example_outputs/demo.jpg
Labels: documentation

#167 Add back CRNN FP16 models as git-lfs tracked files
  models/text_recognition_crnn/text_recognition_CRNN_CH_2023feb_fp16.onnx
  models/text_recognition_crnn/text_recognition_CRNN_EN_2023feb_fp16.onnx
Labels: add model

#169 Change links of table from 'master' to 'main'
  benchmark/color_table.svg
  benchmark/generate_table.py
Labels: documentation

#168 Add gesture classification for handpose estimation
  models/handpose_estimation_mediapipe/README.md
  models/handpose_estimation_mediapipe/demo.py
  models/handpose_estimation_mediapipe/example_outputs/gesture_classification.png
Labels: feature

#174 update sbc notation
  README.md
Labels: documentation

#173 New SBC: add vision five 2
  README.md
  benchmark/README.md
  benchmark/color_table.svg
  benchmark/table_config.yaml
Labels: add hardware

#182 HandPose Estimation: clip palm bbox to (width, height)
  models/handpose_estimation_mediapipe/mp_handpose.py
Labels: bug
